# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # - board: nice_nano_v2
  #   shield: swweeep_left
  # - board: nice_nano_v2
  #   shield: swweeep_right
  
  # - board: nice_nano_v2
  #   shield: temper_dongle
  # - board: nice_nano_v2
  #   shield: temper_left
  #   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  # - board: nice_nano_v2
  #   shield: temper_right

  # - board: seeeduino_xiao_ble
  #   shield: totem_left
  # - board: seeeduino_xiao_ble
  #   shield: totem_right
  # - board: seeeduino_xiao_ble
  #   shield: totem_dongle

  - board: seeeduino_xiao_ble
    shield: settings_reset
  # - board: nice_nano_v2
  #   shield: settings_reset
